name: ci
on:
  push:
    branches:
      - master
    paths:
      - doc/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          cd doc
          pip install -r requirements.txt
          make html
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: |
          cp -rf doc/build/html/* .
          git add -u
          git config --global user.name 'Akihiro Hayashi'
          git config --global user.email 'ahayashi@gatech.edu'
          git commit -am "Auto Deployed"
          git push
